version: '3.8'

services:
  #custom image
  app:
    build:
      args:
        user: jonathan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: copec/laravel-app
    container_name: laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    depends_on:
      - redis
      - queue
    restart: unless-stopped
    networks:
      - docker-laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  minio:
        image: minio/minio
        container_name: minio
        command: server /data --console-address ":9701"
        restart: always
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        volumes:
            - ./minio_data:/data
        ports:
            - 9700:9700
            - 9701:9701
        networks:
            docker-laravel:
#              ipv4_address: 172.16.238.10
#            - docker-laravel
#                ipv4_address: 192.168.1.10

  pgsql:
      image: postgres:12.17
      container_name: pgsql
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - ./.docker/postgresql:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      networks:
        - docker-laravel

  redis:
      image: redis:latest
      container_name: redis
      networks:
        - docker-laravel

  queue:
      build:
        args:
          user: jonathan
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      restart: always
      command: "php artisan queue:work"
      volumes:
        - ./:/var/www/
      depends_on:
        - redis
      networks:
        - docker-laravel

networks:
  docker-laravel:
    driver: bridge
